# Generated by Django 4.2.14 on 2024-07-31 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsModel',
            new_name='News',
        ),
    ]
