# Generated by Django 4.2.14 on 2024-07-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_newsmodel_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='tag',
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='tag',
            field=models.ManyToManyField(related_name='news', to='apis.tag'),
        ),
    ]
