# Generated by Django 4.2.14 on 2024-07-23 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_tag_remove_newsmodel_tag_newsmodel_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsmodel',
            old_name='tag',
            new_name='tags',
        ),
    ]
